apiVersion: apps/v1
kind: Deployment
metadata:
  name: d2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: npostgres:13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        envFrom:
          - configMapRef: 
              name: config1
          - secretRef: 
              name: secret1
